# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0ff8099d69b58b54c61a7c17b48dd59725ae0308b3e2baaf54cec053f9cbea8db75354a6f3187c19675e230e5fa623ca93da5d4539cfc62a1d786852b0ee891a

test:
  secret_key_base: b97e08572318644523197b01521b49556a94544fdfe961fda1c04dc536a24aa0987812d15a73e45eb2007dff93e21b5372836718d1539727f7136ddea14bdb06

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
